-- ============================================================
-- Q1. What is the total revenue generated by male vs. female customers?
-- ============================================================

SELECT Gender,
       SUM(`Purchase Amount (USD)`) AS revenue
FROM customer_shopping_behavior
GROUP BY Gender;


-- ============================================================
-- Q2. Which customers used a discount but still spent more than
-- the average purchase amount?
-- ============================================================

SELECT customer_id,
       `Purchase Amount (USD)`
FROM customer_shopping_behavior
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` >= (
      SELECT AVG(`Purchase Amount (USD)`)
      FROM customer_shopping_behavior
  );


-- ============================================================
-- Q3. Which are the top 5 products with the highest average review rating?
-- ============================================================

SELECT `Item Purchased`,
       ROUND(AVG(`Review Rating`), 2) AS Average_Product_Rating
FROM customer_shopping_behavior
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;


-- ============================================================
-- Q4. Compare the average Purchase Amounts between
-- Standard and Express Shipping.
-- ============================================================

SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS Average_Purchase
FROM customer_shopping_behavior
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;


-- ============================================================
-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue.
-- ============================================================

SELECT `Subscription Status`,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;


-- ============================================================
-- Q6. Which 5 products have the highest percentage of purchases
-- with discounts applied?
-- ============================================================

SELECT `Item Purchased`,
       ROUND(
           100 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS discount_rate
FROM customer_shopping_behavior
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;


-- ============================================================
-- Q7. Segment customers into New, Returning, and Loyal based on
-- previous purchases.
-- ============================================================

WITH customer_type AS (
    SELECT customer_id,
           `Previous Purchases`,
           CASE
               WHEN `Previous Purchases` = 1 THEN 'New'
               WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_shopping_behavior
)

SELECT customer_segment,
       COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;


-- ============================================================
-- Q8. Top 3 most purchased products within each category.
-- ============================================================

WITH item_counts AS (
    SELECT Category,
           `Item Purchased`,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY Category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer_shopping_behavior
    GROUP BY Category, `Item Purchased`
)

SELECT item_rank,
       Category,
       `Item Purchased`,
       total_orders
FROM item_counts
WHERE item_rank <= 3;


-- ============================================================
-- Q9. Are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
-- ============================================================

SELECT `Subscription Status`,
       COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;


-- ============================================================
-- Q10. Revenue contribution of each age group.
-- ============================================================

SELECT
    CASE
        WHEN Age < 20 THEN 'Below 20'
        WHEN Age BETWEEN 20 AND 29 THEN '20-29'
        WHEN Age BETWEEN 30 AND 39 THEN '30-39'
        WHEN Age BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;